### ISSUE TITLE
Word wrapping

### ISSUE THREAD

**Issue by tengotengo** [modesty/pdf2json#18]
{
                    "x": 7.9914062500000025,
                    "y": 3.984375000000001,
                    "w": 1292.917,
                    "clr": 0,
                    "A": "left",
                    "R": [
                        {
                            "T": "SECTION%3A%20CON",
                            "S": -1,
                            "TS": [3, 182, 0, 0]
                        }
                    ]
                },
                {
                    "x": 19.10241171875,
                    "y": 3.984375000000001,
                    "w": 984.6790000000001,
                    "clr": 0,
                    "A": "left",
                    "R": [
                        {
                            "T": "TACT%20LENS",
                            "S": -1,
                            "TS": [3, 182, 0, 0]
                        }
                    ]
                },

This was the "SECTION: CONTACT LENS" string in reference PDF.

**Comment by modesty** [comment]
fixed in v1.0.7

**Comment by matewka** [comment]
I'm still experiencing the unit issue.
In my case the original text says:

"4)narzędzia i urządzenia, których używanie może zagrażać życiu lub zdrowiu:"

while the JSON output is:

```
{
  "x": 4.183,
  "y": 4.811,
  "w": 21.323999999999998,
  "sw": 0.32553125,
  "clr": 0,
  "A": "left",
  "R": [
     {
       "T": "4)na",
       "S": -1,
       "TS": [
         0,
         15,
         0,
         0
       ]
     }
   ]
 },
{
  "x": 6.486,
  "y": 4.811,
  "w": 354.54,
  "sw": 0.32553125,
  "clr": 0,
  "A": "left",
  "R": [
    {
      "T": "rz%C4%99dzia%20i%20urz%C4%85dzenia%2C%20kt%C3%B3rych%20u%C5%BCywanie%20mo%C5%BCe%20zagra%C5%BCa%C4%87%20%C5%BCyciu%20lub%20zdrowiu%3A",
      "S": -1,
      "TS": [
        0,
        15,
        0,
        0
      ]
    }
  ]
}
```

It doesn't seem to add up.
The text from the first object is a part of the first word from the second object (don't mind the "_4)_" - let's just treat it as one word), so **x + w** from the first object should be somewhere between **x** and **x + sw** from the second object, right?

Am I doing something wrong?
